# Generated by Django 4.2.8 on 2024-05-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_remove_article_like_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="nickname",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
