# Generated by Django 4.2.8 on 2024-05-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='cur_nm',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
