# Generated by Django 4.2.8 on 2024-05-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_exchange_cur_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='cur_unit',
            field=models.TextField(unique=True),
        ),
    ]
