# Generated by Django 4.2.8 on 2024-05-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_exchange_cur_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='tts',
            field=models.FloatField(),
        ),
    ]
