# Generated by Django 4.2.8 on 2024-05-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_exchange_tts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido', models.CharField(max_length=10)),
                ('sigungu', models.CharField(max_length=10)),
            ],
        ),
    ]
