# Generated by Django 4.2.8 on 2024-05-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_bankname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='tts',
            field=models.TextField(),
        ),
    ]
