# Generated by Django 4.2.8 on 2024-05-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_alter_exchange_tts'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='deal_bas_r',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
