# Generated by Django 4.2.8 on 2024-05-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('fin_prdt_nm', models.TextField()),
                ('kor_co_nm', models.TextField()),
                ('dcls_month', models.TextField()),
                ('join_way', models.TextField()),
                ('mrtr_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.TextField()),
                ('join_member', models.TextField()),
                ('max_limit', models.TextField()),
            ],
        ),
    ]
