# Generated by Django 4.2.8 on 2024-05-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_depositcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositOptions06',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.TextField(unique=True)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptions12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.TextField(unique=True)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptions24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.TextField(unique=True)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptions36',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.TextField(unique=True)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='fin_co_no',
            field=models.TextField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='fin_prdt_cd',
            field=models.TextField(),
        ),
    ]
