# Generated by Django 4.2.8 on 2024-05-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0004_depositoptions06_depositoptions12_depositoptions24_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositoptions06',
            old_name='fin_co_no',
            new_name='fin_prdt_cd',
        ),
        migrations.RenameField(
            model_name='depositoptions12',
            old_name='fin_co_no',
            new_name='fin_prdt_cd',
        ),
        migrations.RenameField(
            model_name='depositoptions24',
            old_name='fin_co_no',
            new_name='fin_prdt_cd',
        ),
        migrations.RenameField(
            model_name='depositoptions36',
            old_name='fin_co_no',
            new_name='fin_prdt_cd',
        ),
        migrations.RemoveField(
            model_name='depositproducts',
            name='fin_co_no',
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='fin_prdt_cd',
            field=models.TextField(unique=True),
        ),
    ]
