# Generated by Django 4.2.8 on 2024-05-21 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposits', '0006_remove_depositcart_product_depositcart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='like_users',
            field=models.ManyToManyField(related_name='like_prdts', to=settings.AUTH_USER_MODEL),
        ),
    ]
