# Generated by Django 4.2.8 on 2024-05-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finance_goal',
            field=models.CharField(default='금일 저녁식사 해결', max_length=100),
        ),
    ]
