# Generated by Django 4.2.8 on 2024-05-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_finance_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='assets',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
